
BASEDIR = ../..

include $(BASEDIR)/etc/buildsys/config.mk

TARGETS = keyboard

OBJS_keyboard = getkey.o \
		 keyboard.o

LIBS_keyboard = eclipse

INSTALL_keyboard = keyboard.pl

include $(BASEDIR)/etc/buildsys/base.mk


