CC	= gcc
LIBS     = -lXt -lm -lX11
CFLAGS   = -I/usr/include/X11 -g
LIB      = EZX11.a
APP      = app

$(APP): $(APP).o
	$(CC) -o $(APP) $(APP).c $(LIB) $(LIBS)

EZX11.a: initx.o windowx.o colorx.o grey.o drawx.o textx.o cursorx.o
	ar cru EZX11.a initx.o windowx.o colorx.o grey.o drawx.o textx.o cursorx.o
	ranlib EZX11.a

EZX11.so: initx.o windowx.o colorx.o grey.o drawx.o textx.o cursorx.o
	ar cru EZX11.a initx.o windowx.o colorx.o grey.o drawx.o textx.o cursorx.o
	ranlib EZX11.a
