
BASEDIR = ..

SUBDIRS = graphviz keyboard icp_shell gridvis

include $(BASEDIR)/etc/buildsys/config.mk
include $(BASEDIR)/etc/buildsys/rules.mk

nfo:
	$(SILENT) echo -e " ... have eclipse: $(HAVE_ECLIPSE)" 
	$(SILENT) echo -e " ... ?eclipse-CLP: $(ECLIPSE_CLP)" 
	$(SILENT) echo -e " ...  eclipse-LOC: $(ECLIPSE_LOC)" 
	$(SILENT) echo -e " ...  ECL-VERSION: $(ECLIPSE_VERSION)" 
	$(SILENT) echo -e " ...     ECL-ARCH: $(ECLIPSE_ARCH)" 
	$(SILENT) echo -e " ...     ECL-PATH: $(ECLIPSE_PATH)" 
