CC = gcc
CFLAGS = -g
LIBS = EZX11.a -lXt -lm -lX11
SRCS = pole_balance.c
OBJS = pole_balance.o
GAMESRCS = pole_game.c
GAMEOBJS = pole_game.o

pole_game: $(OBJS) $(GAMEOBJS)
	$(CC) $(CFLAGS) -o pole_game $(OBJS) $(GAMEOBJS) $(LIBS)

depend:
	makedepend -- $(CFLAGS) -- $(SRCS) $(GAMESRCS) -I. \
	-I/usr/local/include -I/usr/local/include/gcc \
	-I/usr/include

#	-I/usr/local/gcc-2.95.2/sparc-sun-solaris2.7/include/

clean:
	/bin/rm *.o pole_game

.c.o:
	$(CC) $(CFLAGS) -c $<

# DO NOT DELETE THIS LINE -- make depend depends on it.

pole_balance.o: pole_balance.h /usr/include/stdio.h /usr/include/features.h
pole_balance.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
pole_balance.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
pole_balance.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
pole_balance.o: /usr/include/libio.h /usr/include/_G_config.h
pole_balance.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
pole_balance.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
pole_balance.o: /usr/include/sys/types.h /usr/include/time.h
pole_balance.o: /usr/include/endian.h /usr/include/bits/endian.h
pole_balance.o: /usr/include/sys/select.h /usr/include/bits/select.h
pole_balance.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
pole_balance.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
pole_balance.o: /usr/include/alloca.h /usr/include/math.h
pole_balance.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
pole_balance.o: /usr/include/bits/mathcalls.h EZX11.h /usr/include/strings.h
pole_balance.o: /usr/include/X11/Xlib.h /usr/include/X11/X.h
pole_balance.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
pole_balance.o: /usr/include/X11/Xutil.h /usr/include/X11/keysym.h
pole_balance.o: /usr/include/X11/keysymdef.h
pole_game.o: pole_balance.h /usr/include/stdio.h /usr/include/features.h
pole_game.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
pole_game.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
pole_game.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
pole_game.o: /usr/include/libio.h /usr/include/_G_config.h
pole_game.o: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
pole_game.o: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
pole_game.o: /usr/include/sys/types.h /usr/include/time.h
pole_game.o: /usr/include/endian.h /usr/include/bits/endian.h
pole_game.o: /usr/include/sys/select.h /usr/include/bits/select.h
pole_game.o: /usr/include/bits/sigset.h /usr/include/bits/time.h
pole_game.o: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
pole_game.o: /usr/include/alloca.h /usr/include/math.h
pole_game.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
pole_game.o: /usr/include/bits/mathcalls.h EZX11.h /usr/include/strings.h
pole_game.o: /usr/include/X11/Xlib.h /usr/include/X11/X.h
pole_game.o: /usr/include/X11/Xfuncproto.h /usr/include/X11/Xosdefs.h
pole_game.o: /usr/include/X11/Xutil.h /usr/include/X11/keysym.h
pole_game.o: /usr/include/X11/keysymdef.h
